name        : librsvg
version     : 2.40.9
release     : 8
source      :
    - http://ftp.acc.umu.se/pub/GNOME/sources/librsvg/2.40/librsvg-2.40.9.tar.xz : 13964c5d35357552b47d365c34215eee0a63bf0e6059b689f048648c6bf5f43a
homepage    : http://www.live.gnome.org/LibRsvg
license     :
    - GPL-2.0
    - LGPL-2.1
summary     : Library to render SVG files using cairo
component   : desktop.library
optimize    : speed
patterns    :
    - devel:
        - /usr/bin
builddeps   :
    - pkgconfig(pangocairo)
    - pkgconfig(cairo-png)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(libcroco-0.6)
    - vala
description : |
    Library to render SVG files using cairo.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
