name       : librsvg
version    : 2.40.16
release    : 11
source     :
    - http://ftp.gnome.org/pub/gnome/sources/librsvg/2.40/librsvg-2.40.16.tar.xz : d48bcf6b03fa98f07df10332fb49d8c010786ddca6ab34cbba217684f533ff2e
homepage   : http://www.live.gnome.org/LibRsvg
license    :
    - GPL-2.0
    - LGPL-2.1
summary    : Library to render SVG files using cairo
component  : desktop.library
optimize   : speed
patterns   :
    - devel :
        - /usr/bin
builddeps  :
    - pkgconfig(pangocairo)
    - pkgconfig32(pangocairo)
    - pkgconfig(cairo-png)
    - pkgconfig32(cairo-png)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig32(gdk-pixbuf-2.0)
    - pkgconfig(libcroco-0.6)
    - pkgconfig32(libcroco-0.6)
    - pkgconfig32(xshmfence)
    - libgcc-32bit
    - glibc-32bit-devel
    - vala
emul32     : yes
description: |
    Library to render SVG files using cairo.
setup      : |
    %configure --disable-static --prefix=/usr
build      : |
    %make
install    : |
    %make_install
