name       : librsvg
version    : 2.40.20
release    : 15
source     :
    - http://ftp.gnome.org/pub/gnome/sources/librsvg/2.40/librsvg-2.40.20.tar.xz : cff4dd3c3b78bfe99d8fcfad3b8ba1eee3289a0823c0e118d78106be6b84c92b
homepage   : http://www.live.gnome.org/LibRsvg
license    :
    - GPL-2.0
    - LGPL-2.1
summary    : Library to render SVG files using cairo
component  : desktop.library
optimize   : speed
patterns   :
    - devel :
        - /usr/bin
builddeps  :
    - pkgconfig32(pangocairo)
    - pkgconfig32(cairo-png)
    - pkgconfig32(fontconfig)
    - pkgconfig32(freetype2)
    - pkgconfig32(gdk-pixbuf-2.0)
    - pkgconfig32(glib-2.0)
    - pkgconfig32(gl)
    - pkgconfig32(libcroco-0.6)
    - pkgconfig32(libpng)
    - pkgconfig32(libxml-2.0)
    - pkgconfig32(xdamage)
    - pkgconfig32(xshmfence)
    - vala
emul32     : yes
description: |
    Library to render SVG files using cairo.
setup      : |
    unset LD_AS_NEEDED
    %configure --disable-static --prefix=/usr
build      : |
    unset LD_AS_NEEDED
    %make
install    : |
    unset LD_AS_NEEDED
    %make_install
