name       : librsvg
version    : 2.46.1
release    : 26
source     :
    - https://download.gnome.org/sources/librsvg/2.46/librsvg-2.46.1.tar.xz : 2da1f2547a63a24ead121ad345011d5fd4f038ef46f74712ec82a1e85ec67643
homepage   : https://wiki.gnome.org/Projects/LibRsvg
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
summary    : Library to render SVG files using Cairo
description: |
    A small library to render Scalable Vector Graphics (SVG), associated with the GNOME Project. It renders SVG files to Cairo surfaces. Cairo is the 2D, antialiased drawing library that GNOME uses to draw things to the screen or to generate output for printing
component  : desktop.library
optimize   : speed
emul32     : yes
patterns   :
    - devel :
        - /usr/bin
builddeps  :
    - pkgconfig32(pangocairo)
    - pkgconfig32(cairo-png)
    - pkgconfig32(fontconfig)
    - pkgconfig32(gdk-pixbuf-2.0)
    - pkgconfig32(glib-2.0)
    - pkgconfig32(gl)
    - pkgconfig32(libcroco-0.6)
    - pkgconfig32(libpng)
    - pkgconfig32(libxml-2.0)
    - pkgconfig32(xdamage)
    - pkgconfig32(xshmfence)
    - cargo
    - gtk-doc
    - vala
setup      : |
    flags='--disable-static --enable-vala'
    if [ ! -z $EMUL32BUILD ]; then
        flags+=' --host=i686-unknown-linux-gnu'
    fi
    %configure $flags
build      : |
    %make
install    : |
    %make_install
    rm -rf $installdir/usr/share/doc
