name       : librsvg
version    : 2.50.4
release    : 41
source     :
    - https://download.gnome.org/sources/librsvg/2.50/librsvg-2.50.4.tar.xz : 3ab6107b4b972c10b5c8029ad8f3b42b3a0e77beae0ae368910f2189576140a3
homepage   : https://wiki.gnome.org/Projects/LibRsvg
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.library
summary    : Library to render SVG files using Cairo
description: |
    A small library to render Scalable Vector Graphics (SVG), associated with the GNOME Project. It renders SVG files to Cairo surfaces. Cairo is the 2D, antialiased drawing library that GNOME uses to draw things to the screen or to generate output for printing
optimize   : speed
emul32     : yes
patterns   :
    - devel :
        - /usr/bin
builddeps  :
    - pkgconfig32(fontconfig)
    - pkgconfig32(gdk-pixbuf-2.0)
    - pkgconfig32(libpng)
    - pkgconfig32(libxml-2.0)
    - pkgconfig32(pango)
    - pkgconfig32(xdamage)
    - pkgconfig32(xshmfence)
    - cargo
    - gtk-doc
    - vala
setup      : |
    flags='--disable-static --enable-vala'
    if [ ! -z $EMUL32BUILD ]; then
        flags+=' --host=i686-unknown-linux-gnu'
    fi
    %configure $flags
build      : |
    %make
install    : |
    %make_install
    rm -rf $installdir/usr/share/doc
