name       : librsvg
version    : 2.56.3
release    : 53
source     :
    - https://download.gnome.org/sources/librsvg/2.56/librsvg-2.56.3.tar.xz : 5a328048a02d014645cd27f61140f4e0b11280fb2c7f2a21864fe0c59ac1ce88
homepage   : https://wiki.gnome.org/Projects/LibRsvg
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.library
summary    : Library to render SVG files using Cairo
description: |
    A small library to render Scalable Vector Graphics (SVG), associated with the GNOME Project. It renders SVG files to Cairo surfaces. Cairo is the 2D, antialiased drawing library that GNOME uses to draw things to the screen or to generate output for printing
optimize   : speed
networking : yes
emul32     : yes
patterns   :
    - devel :
        - /usr/bin
builddeps  :
    - pkgconfig32(fontconfig)
    - pkgconfig32(gdk-pixbuf-2.0)
    - pkgconfig32(libpng)
    - pkgconfig32(libxml-2.0)
    - pkgconfig32(pango)
    - pkgconfig32(xdamage)
    - pkgconfig32(xshmfence)
    - cargo
    - gi-docgen
    - python-docutils # man
    - vala
setup      : |
    flags='--disable-static --enable-vala'
    if [ ! -z $EMUL32BUILD ]; then
        flags+=' --host=i686-unknown-linux-gnu'
    fi
    %configure $flags
build      : |
    %make
install    : |
    %make_install
    rm -rf $installdir/usr/share/doc
