name       : librsvg
version    : 2.40.17
release    : 12
source     :
    - http://ftp.gnome.org/pub/gnome/sources/librsvg/2.40/librsvg-2.40.17.tar.xz : e6f6c5cbecc405bb945c7cd15061276035ae3173bbb3bb25e8a916779c7f69cc
homepage   : http://www.live.gnome.org/LibRsvg
license    :
    - GPL-2.0
    - LGPL-2.1
summary    : Library to render SVG files using cairo
component  : desktop.library
optimize   : speed
patterns   :
    - devel :
        - /usr/bin
builddeps  :
    - pkgconfig32(pangocairo)
    - pkgconfig32(cairo-png)
    - pkgconfig32(gdk-pixbuf-2.0)
    - pkgconfig32(glib-2.0)
    - pkgconfig32(gl)
    - pkgconfig32(libcroco-0.6)
    - pkgconfig32(libpng)
    - pkgconfig32(libxml-2.0)
    - pkgconfig32(xdamage)
    - pkgconfig32(xshmfence)
    - vala
emul32     : yes
description: |
    Library to render SVG files using cairo.
setup      : |
    %configure --disable-static --prefix=/usr
build      : |
    %make
install    : |
    %make_install
