name       : librsvg
version    : 2.40.18
release    : 13
source     :
    - http://ftp.gnome.org/pub/gnome/sources/librsvg/2.40/librsvg-2.40.18.tar.xz : bfc8c488c89c1e7212c478beb95c41b44701636125a3e6dab41187f1485b564c
homepage   : http://www.live.gnome.org/LibRsvg
license    :
    - GPL-2.0
    - LGPL-2.1
summary    : Library to render SVG files using cairo
component  : desktop.library
optimize   : speed
patterns   :
    - devel :
        - /usr/bin
builddeps  :
    - pkgconfig32(pangocairo)
    - pkgconfig32(cairo-png)
    - pkgconfig32(gdk-pixbuf-2.0)
    - pkgconfig32(glib-2.0)
    - pkgconfig32(gl)
    - pkgconfig32(libcroco-0.6)
    - pkgconfig32(libpng)
    - pkgconfig32(libxml-2.0)
    - pkgconfig32(xdamage)
    - pkgconfig32(xshmfence)
    - vala
emul32     : yes
description: |
    Library to render SVG files using cairo.
setup      : |
    %configure --disable-static --prefix=/usr
build      : |
    %make
install    : |
    %make_install
